### ISSUE TITLE
test_markers not testing properly

### ISSUE THREAD

**Issue by eLRuLL** [jbasko/pytest-random-order#18]
I was checking the tests in `test_makers`, specifically `test_marker_disables_random_order_in_module` and `test_marker_disables_random_order_in_class` and saw you are calling:

    result = testdir.runpytest('--random-order-bucket=module', '-v')
    result.assert_outcomes(passed=20)

Are those lines really necessary? If they are, I would really appreciate if you could explain how they are relevant for the test.

Thanks

**Comment by jbasko** [comment]
Thanks. I think it was from the first or second day when I wasn't sure if the plugin is actually running, accepting command line options etc., so the sub-test suite was being run twice. And then I copied those lines across to the other test method. Have removed the redundant calls now.
