### ISSUE TITLE
Do not randomize initial tests

### ISSUE THREAD

**Issue by michalsimek** [jbasko/pytest-random-order#29]
Hi,

I would like to use this module for test randomization but I need to run some initial setup first before other tests. I would expect that It is possible to move them to different file and never randomize files but will be the best if I can simply mark tests which shouldn't be randomized and should run first before others.

Thanks

**Comment by jbasko** [comment]
Do you want certain tests to run first or do you want some setup to always run first? If you want some setup to run first, you want to look at pytest fixtures with `autouse=True`. Did I understand you correctly?

**Comment by jbasko** [comment]
Closing due to lack of feedback.
