### ISSUE TITLE
Add tests to PyPI sources

### ISSUE THREAD

**Issue by seifertm** [jbasko/pytest-random-order#35]
I am currently trying to package `pytest-random-order-1.0.2` for Gentoo Linux. Gentoo packages are generally compiled from source. The installation process involves a test phase which executes the package's tests in order to verify that the installed software is working. However, the source tarball for `pytest-random-order-1.0.2` does not include the tests.

Would it be possible to add tests to the PyPI source tarball for future releases?

**Comment by jbasko** [comment]
Hi, yes I'll look into it. Thanks for pointing it out.

**Comment by jbasko** [comment]
Added in v1.0.3
