### ISSUE TITLE
Keep random-order-bucket=none

### ISSUE THREAD

**Issue by matejcik** [jbasko/pytest-random-order#40]
The `none` value for random-order-bucket is deprecated.

Here's a usecase that IMHO warrants keeping it.

In our project, the top-level `setup.cfg` enables random-order by adding `addopts = --random-order`. From that point on, it's not possible to disable randomization on the command line: using `-p no:random_order` deactivates the plugin, which makes the `--random-order` argument invalid.

The only option here is to specify `--random-order-bucket=none`.

**Comment by jbasko** [comment]
Thanks @matejcik for the use case. I will not remove it in future.
