### ISSUE TITLE
Documentation appears to be wrong

### ISSUE THREAD

**Issue by Mrodent** [jbasko/pytest-random-order#45]
Here https://pythonhosted.org/pytest-random-order/ an intro to this (very useful) plugin says that "The plugin is enabled by default.".

This intro by Jazeps Basko is dated 2016. Maybe that was how it worked then. It doesn't work "by default" now, at least not on my OS (W10).

**Comment by jbasko** [comment]
This has been now marked for destruction as documentation uploading is no longer supported there (at least that's what I read on pypi.org).
